steps:
# Build and deploy Backend
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/battleship-backend:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/battleship-backend:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'battleship-backend', '--image', 'gcr.io/$PROJECT_ID/battleship-backend:$COMMIT_SHA', '--region', 'us-central1']
  images:
  - 'gcr.io/$PROJECT_ID/battleship-backend:$COMMIT_SHA'

# Build and deploy frontend
- name: node:16.18.1
  entrypoint: npm
  args: ["install", "--prefix", "./frontend"]
- name: node:16.18.1
  entrypoint: npm
  args: ["--prefix", "./frontend", "run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "./frontend/app.yaml"]
timeout: "1600s"