steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy ./backend/app.yaml']
  timeout: '1600s'
- name: node:16.18.1
  entrypoint: npm
  args: ["install", "--prefix", "./frontend"]
- name: node:16.18.1
  entrypoint: npm
  args: ["--prefix", "./frontend", "run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "./frontend/app.yaml"]
timeout: "1600s"